title: Wei, Z's portfolio
# Theme: default | navy | teal | dark | burgundy
site_theme: dark
email: weiz@janelia.hhmi.org
description: Ziqiang Wei's website
baseurl: ""
url: ""
twitter_username:
github_username:

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty
include: ['_pages', '.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'Gruntfile.js', 'README.md', 'vendor', '.bundle']
